events {
    worker_connections 1024;
}

http {
    upstream flask_app {
        server app:8000;
    }

    server {
        listen 80;
        server_name parssnab.live;

        auth_basic "Domain Scanner";
        auth_basic_user_file /etc/nginx/.htpasswd;

        # Глобальные лимиты
        client_max_body_size 500M;
        client_body_timeout 900s;
        client_header_timeout 900s;
        proxy_read_timeout 900s;
        proxy_send_timeout 900s;
location / {
    client_body_buffer_size 1M;
    client_body_temp_path /tmp/nginx_upload;
    proxy_pass http://flask_app;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    client_max_body_size 500M;
    client_body_timeout 1200s;      # 20 минут
    proxy_read_timeout 1200s;
    proxy_send_timeout 1200s;
    proxy_connect_timeout 60s;

    proxy_request_buffering on;     # важно для больших файлов
}
    }
}
